#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   p <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_p`. Typically I'm using it like:
#
#    s gitu<tab>/repo<tab>
#
# ...to quickly jump into gituser/repository, for example.

cd "$PROJECTS/$1"
