#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   p <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_p`. Typically I'm using it like:
#
#    s gitu<tab>/repo<tab>
#
# ...to quickly jump into gituser/repository, for example.

p () {
  local root="$PROJECTS"
  local query="$root/$1"

  if [[ -d $query ]] && [ "$root/" != "$query" ]
  then
	 cd $query
  else
	local dir
	dir=$(find $root -path '*/\.*' -prune \
	                 -o -type d -print 2> /dev/null | sed "s;$root/;;g" | fzf +m -q "$1") &&
	cd "$root/$dir"
  fi
}
