#!/bin/zsh
#
# This lets you quickly jump into a sites directory.
#
# Type:
#
#   s <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_s`. Typically I'm using it like:
#
#    s hai<tab>
#
# ...to quickly jump into hails.info, for example.


s() {
  local root="$SITES"
  local query="$root/$1"
  
  if [[ -d $query ]] && [ "$root/" != "$query" ]
  then
	 cd $query
  else
	local dir
	dir=$(find $root -path '*/\.*' -prune \
                     -o -type d -print 2> /dev/null | sed "s;$root/;;g" | fzf +m -q "$1") &&
	cd "$root/$dir"
  fi
}
