export PATH="$PATH:/opt/flutter/bin"
export PATH="$PATH:/opt/android-studio/bin"
export PATH="$PATH:/opt/Android/Sdk/"
export PATH="$PATH:/opt/Android/Sdk/platform-tools"
export ANDROID_SDK_ROOT="/opt/Android/Sdk/"
