#!/usr/bin/env bash

setup_gitconfig () {
  local local_git_config=modules/git/gitconfig.local
  if ! [ -f $local_git_config ]
  then
    # git_credential='cache'
    if platform::is_osx
    then
      git_credential='osxkeychain'
    fi

    prompt::author

    sed -e "s/AUTHORNAME/$GIT_AUTHOR_NAME/g" \
      -e "s/AUTHOREMAIL/$GIT_AUTHOR_EMAIL/g" \
      $local_git_config.tmpl > $local_git_config

    # Only record a credential helper when one was actually chosen. An empty
    # `helper =` line would reset git's accumulated helper list (gitconfig.local
    # is included last), wiping e.g. gh's helper on Linux where git_credential
    # is unset.
    if [ -n "${git_credential:-}" ]
    then
      git config --file "$local_git_config" credential.helper "$git_credential"
    fi

    log::success "generated $local_git_config"
  else
    log::success 'skipped gitconfig generation as present'
  fi
}


setup_github_ssh_rewrite () {
  # The tracked gitconfig includes ~/.gitconfig.github-ssh (missing file =
  # silently skipped). Generate it only where the ssh config has a Host entry
  # covering github.com — github::set_ssh_key writes one when it provisions a
  # key. Headless workers (gantry) never have that entry and must stay on
  # HTTPS: a global https->ssh rewrite there collides with their ssh->https
  # rule and git-lfs resolves the duplicate alias nondeterministically,
  # killing ~50% of pushes in LFS repos. The generated content must stay
  # byte-identical to ensure_github_ssh_rewrite in
  # modules/dotfiles-autoupdate/update.sh.
  if grep -qsiE '^[[:space:]]*Host[[:space:]]+([^#]*[[:space:]])?github\.com([[:space:]]|$)' \
    "$HOME/.ssh/config"; then
    printf '%s\n' \
      '# Generated by the dotfiles git module (modules/git/setup.sh; ensured daily' \
      '# by modules/dotfiles-autoupdate/update.sh): this host has an authorised' \
      '# GitHub SSH key ("Host github.com" in ~/.ssh/config), so HTTPS remotes' \
      '# rewrite to SSH. See the include comment in modules/git/gitconfig.' \
      '[url "git@github.com:"]' \
      '	insteadOf = https://github.com/' > "$HOME/.gitconfig.github-ssh"
    log::success "generated ~/.gitconfig.github-ssh (HTTPS -> SSH rewrite)"
  else
    log::success "skipped ~/.gitconfig.github-ssh (no GitHub SSH key on this host)"
  fi
}


. "$DOTFILES/scripts/core/main.sh"
. "$DOTFILES/modules/git/setup.prompt.sh"
. "$DOTFILES/modules/git/setup.github.sh"
setup_gitconfig
setup_github_ssh_rewrite

install::package "Git LFS" "git-lfs"
install::release_binary "sops" "sops" "getsops/sops" \
  "https://github.com/getsops/sops/releases/download/@TAG@/sops-@TAG@.linux.@ARCH_DEB@"
# Glassine (sops-backed git encryption, replaces transcrypt): a single script
# with no release artifacts — install straight from the repo's main branch.
if platform::command_exists glassine; then
  log::success "Glassine"
else
  mkdir -p "$HOME/.local/bin"
  log::execute "curl -fsSL https://raw.githubusercontent.com/DJRHails/glassine/main/glassine -o \$HOME/.local/bin/glassine && chmod +x \$HOME/.local/bin/glassine" "Glassine"
fi
github::install_cli

# gh-stack: GitHub's official stacked-PR extension (needs gh >= 2.90 and an
# authenticated gh — extension installs clone through the API).
if ! platform::command_exists gh; then
  log::warning "gh not on PATH; skipping gh-stack extension"
elif gh extension list 2> /dev/null | grep -q 'github/gh-stack'; then
  log::success "gh-stack extension"
elif gh auth status > /dev/null 2>&1; then
  log::execute "gh extension install github/gh-stack" "gh-stack extension"
else
  log::warning "gh not authenticated; skipping gh-stack extension (gh extension install github/gh-stack)"
fi

# Hook enforcement: point init.templateDir at ~/.git-template and populate it
# with prek's pre-commit shim, so every future clone/init gets hooks — the
# shim no-ops in repos without a pre-commit config. Then install hooks for
# this repo itself, which already has one. templateDir goes in gitconfig.local
# as an absolute path: git would tilde-expand `~/.git-template`, but prek's
# init-template-dir check reads the configured value literally.
if platform::command_exists prek; then
  git config --file "$DOTFILES/modules/git/gitconfig.local" \
    init.templateDir "$HOME/.git-template"
  prek init-template-dir "$HOME/.git-template" > /dev/null 2>&1
  log::result $? "prek template dir (~/.git-template)"

  # prek installs into .git/hooks and refuses to run at all while core.hooksPath
  # is set ("Cowardly refusing to install hooks with `core.hooksPath` set") —
  # git would ignore what it wrote. The legacy pre-commit ~/.git-hooks setup left
  # that key behind on some hosts, silently disabling this repo's secret scanning
  # there. Clear it wherever it lives before installing.
  if [ -n "$(git config --file "$HOME/.gitconfig.local" --get-all core.hooksPath)" ]; then
    git config --file "$HOME/.gitconfig.local" --unset-all core.hooksPath
    log::success "cleared core.hooksPath from ~/.gitconfig.local (prek needs .git/hooks)"
  fi
  if [ -n "$(git -C "$DOTFILES" config --local --get-all core.hooksPath)" ]; then
    git -C "$DOTFILES" config --local --unset-all core.hooksPath
    log::success "cleared core.hooksPath from .files/.git/config"
  fi

  prek_err=$(cd "$DOTFILES" && prek install 2>&1 > /dev/null)
  if [ -n "$prek_err" ]; then
    log::error "prek install (.files): $prek_err"
  else
    log::success "prek install (.files)"
  fi
else
  log::warning "prek not on PATH (rust module installs it); skipping git hook setup"
fi

if [ "$skipQuestions" != true ]; then
  feedback::ask_for_confirmation "Do you want to setup github?"
  if feedback::answer_is_yes
  then
    install::package "GPG" "gpg"
    github::setup
    # github::setup may have just provisioned the SSH key ("Host github.com"
    # block); re-check so the HTTPS -> SSH rewrite lands in the same run.
    setup_github_ssh_rewrite
  fi
fi
